/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as FoldersRouteImport } from './routes/folders'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoldersIndexRouteImport } from './routes/folders.index'
import { Route as MeetingIdRouteImport } from './routes/meeting.$id'
import { Route as FoldersFolderIdRouteImport } from './routes/folders.$folderId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersRoute = FoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersIndexRoute = FoldersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoldersRoute,
} as any)
const MeetingIdRoute = MeetingIdRouteImport.update({
  id: '/meeting/$id',
  path: '/meeting/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersFolderIdRoute = FoldersFolderIdRouteImport.update({
  id: '/$folderId',
  path: '/$folderId',
  getParentRoute: () => FoldersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/folders': typeof FoldersRouteWithChildren
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/folders/': typeof FoldersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/folders': typeof FoldersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/folders': typeof FoldersRouteWithChildren
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/meeting/$id': typeof MeetingIdRoute
  '/folders/': typeof FoldersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/folders'
    | '/meetings'
    | '/onboarding'
    | '/settings'
    | '/folders/$folderId'
    | '/meeting/$id'
    | '/folders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/meetings'
    | '/onboarding'
    | '/settings'
    | '/folders/$folderId'
    | '/meeting/$id'
    | '/folders'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/folders'
    | '/meetings'
    | '/onboarding'
    | '/settings'
    | '/folders/$folderId'
    | '/meeting/$id'
    | '/folders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FoldersRoute: typeof FoldersRouteWithChildren
  MeetingsRoute: typeof MeetingsRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  MeetingIdRoute: typeof MeetingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders': {
      id: '/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof FoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/': {
      id: '/folders/'
      path: '/'
      fullPath: '/folders/'
      preLoaderRoute: typeof FoldersIndexRouteImport
      parentRoute: typeof FoldersRoute
    }
    '/meeting/$id': {
      id: '/meeting/$id'
      path: '/meeting/$id'
      fullPath: '/meeting/$id'
      preLoaderRoute: typeof MeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdRouteImport
      parentRoute: typeof FoldersRoute
    }
  }
}

interface FoldersRouteChildren {
  FoldersFolderIdRoute: typeof FoldersFolderIdRoute
  FoldersIndexRoute: typeof FoldersIndexRoute
}

const FoldersRouteChildren: FoldersRouteChildren = {
  FoldersFolderIdRoute: FoldersFolderIdRoute,
  FoldersIndexRoute: FoldersIndexRoute,
}

const FoldersRouteWithChildren =
  FoldersRoute._addFileChildren(FoldersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FoldersRoute: FoldersRouteWithChildren,
  MeetingsRoute: MeetingsRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  MeetingIdRoute: MeetingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
